name: receipts
description: Keep all your receipts in one place
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cloud_firestore: ^3.1.10
  equatable: ^2.0.3
  file_picker: ^4.5.1
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  flex_color_scheme: ^5.0.0-dev.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  go_router: ^3.0.3
  google_fonts: ^2.3.1
  google_mobile_ads: ^1.1.0
  google_sign_in: ^5.2.4
  hydrated_bloc: ^8.0.0
  intl: ^0.17.0
  path_provider: ^2.0.9
  uuid: ^3.0.6
  

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0  

flutter:
  uses-material-design: true
  generate: true
