// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Firebase details for specific platform
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdZwWwO93sGcbOf4cNjllz4yuoWGN1ElQ',
    appId: '1:1026746294233:android:daa8daacbf2d2d95cc43c8',
    messagingSenderId: '1026746294233',
    projectId: 'receipts-1ad63',
    storageBucket: 'receipts-1ad63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvNdvLoLB5DRrPq_Fg5eYDWUkN1ib8YQo',
    appId: '1:1026746294233:ios:377d3722e4b872b4cc43c8',
    messagingSenderId: '1026746294233',
    projectId: 'receipts-1ad63',
    storageBucket: 'receipts-1ad63.appspot.com',
    iosClientId:
        '1026746294233-cdlf47fa3rjp4ql0cee23or6u6mqu712.apps.googleusercontent.com',
    iosBundleId: 'com.hextools.receipts',
  );
}
